import clsx from 'clsx'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import './globals.css'

export interface NavItems {
  name: string
  href: string
}

const nav: NavItems[] = [
  {
    name: 'Home',
    href: '/',
  },
  {
    name: 'About',
    href: '/about',
  },
]

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={clsx('bg-gray-900 text-white', inter.className)}>
        <NavBar nav={nav} />
        {children}
      </body>
    </html>
  )
}
